fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User

    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        mailer:       fos_user.mailer.twig_swift
        user_manager: sonata.user.orm.user_manager

    from_email:
        address:        noreply@podzamenu.ru
        sender_name:    Podzamenu

    registration:
        form:
            type: app_user_registration

        confirmation:
            enabled: true
            template:   ApplicationSonataUserBundle:Registration:email.txt.twig
