app_main:
    resource: "@ApplicationMainBundle/Resources/config/routing.yml"
    prefix:   /
    requirements:
        _locale: en|ru

sonata_user_security:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/sonata_security_1.xml"
    prefix: /login

sonata_user_resetting:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile


